title:              my Blog
email:              unijay12@gmail.com
description:        A Blog Theme by Jay Prakash
author:             Jay Prakash
baseurl:            "/"
url:                "https://jayprakash02.github.io"

# Social Profiles
twitter_username:   
github_username:    jayprakash02
facebook_username:  jp.star.02
instagram_username: jay_prakash02
linkedin_username:  jay-prakash-002

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-87YBE6JQHX # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
theme: jekyll-theme-architect
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
